services:
  postgres:
    image: postgres:16-alpine
    container_name: edusync_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edusync
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - edusync_network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: edusync_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/edusync
      SECRET_KEY: mi-super-secreto-cambiame-en-produccion
    depends_on:
      - postgres
    networks:
      - edusync_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: edusync_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - edusync_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  edusync_network:
    driver: bridge
